# https://just.systems/man/en/
# Just is inspired by makefile syntay but avoids some ot its [caveats](https://just.systems/man/en/chapter_75.html).

install:
    pnpm install --frozen-lockfile

build:
    pnpm build

start:
    pnpm start

test:
    pnpm test -- --collect-coverage

lint:
    pnpm lint

fix:
    pnpm fix
