build:
    @echo "Installing Roadrunner..."
    yes | vendor/bin/rr get --location bin/
    @echo "Installing dependencies..."
    symfony composer install

start:
    docker compose up -d
    bin/rr serve -c .rr.dev.yaml --debug
    
fix:
    vendor/bin/php-cs-fixer fix --diff
    
    
static-analysis:
    vendor/bin/parallel-lint src public migrations config
    vendor/bin/php-cs-fixer fix --dry-run --diff
    vendor/bin/psalm
    
test: static-analysis
    echo "Running tests..."
    vendor/bin/phpunit