develop:
    docker compose up -d
    docker compose ps
    
    @echo "Trusting certificates..."
    symfony server:ca:install
    @echo "Installing dependencies..."
    symfony composer install
    symfony serve