---
name: Tests
on:
    push:
        branches:
            - main
    pull_request:
      types:
        - opened # To ensure we can have dummy env environments
        - reopened
        - synchronize # pushed commits
    # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
    merge_group:

concurrency:
  group: tests-${{ github.ref }}
  # Let them run, so we will see error markings on every commit
  # Subject to change
  cancel-in-progress: false
  
permissions:
  ## see https://github.com/marketplace/actions/composer-lock-diff
  pull-requests: write
  contents: read
  
jobs:
  environment:
    name: Install on OS
    strategy: 
      matrix:
        os: [ ubuntu-latest, macos-latest ] # windows-latest does not work
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0

  backend:
    name: Backend
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Comment composer.lock diff
        if: github.event_name == 'pull_request'
        uses: WyriHaximus/github-action-composer.lock-diff@v2
        with:
          workingDirectory: backend/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
      - run: devbox run --pure just backend/build
      - run: devbox run --pure just backend/security-check
      - run: devbox run --pure just backend/static-analysis
      - name: Start & wait for db to be ready
        run: devbox run --pure just backend/start && devbox run --pure ./wait-until.sh "mysql --host=127.0.0.1 --port=23306 --database=app_test --user=test --password=test -e \"SHOW TABLES\"" 120
      - run: devbox run --pure just backend/test fail-fast=true

  frontend:
    name: Frontend
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
      - name: Install dependencies
        run: devbox run --pure just frontend/install
      - name: Lint
        run: devbox run --pure just frontend/lint
      - name: Unit Tests
        run: devbox run --pure just frontend/test
      - name: Build
        run: devbox run --pure just frontend/build