---
name: Tests
on:
    push:
        branches:
            - main
    pull_request:
      types:
        - opened # To ensure we can have dummy env environments
        - reopened
        - synchronize # pushed commits

concurrency:
  group: tests-${{ github.ref }}
  # Let them run, so we will see error markings on every commit
  # Subject to change
  cancel-in-progress: false
  
permissions:
  ## see https://github.com/marketplace/actions/composer-lock-diff
  pull-requests: write
  contents: read
  
jobs:
  comment-composer-lock-diff:
    name: Comment composer.lock diff
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Comment composer.lock diff
        uses: WyriHaximus/github-action-composer.lock-diff@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  static-analysis:
    name: Backend static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
        with:
          enable-cache: true
      - name: Build
        run: devbox run just build
      - run: devbox run just backend/static-analysis
  
  backend-unit-tests:
    name: Backend Unit-Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
        with:
          enable-cache: true
      - name: Build
        run: devbox run just build
      - run: devbox run just backend/test-unit fail-fast=true
  
  backend-tests:
    name: Backend test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
        with:
          enable-cache: true
      - name: Build
        run: devbox run just build
      - name: Start
        run: devbox run just backend/start && devbox run ./wait-until.sh "mysql --host=127.0.0.1 --port=23306 --database=app_test --user=test --password=test -e \"SHOW TABLES\"" 120
      - run: devbox run just backend/test fail-fast=true
        
  security-check:
    name: Security check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.5.0
        with:
          enable-cache: true
      - name: Build
        run: devbox run just backend/security-check